app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int( user_id))

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(255), index = True)
    email = db.Column(db.String(255), unique = True, index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))
    pitches = db.relationship('Pitch', backref = 'user', lazy = 'dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)


    def __repr__(self):
        return f'User {self.username}'

class Pitch(db.Model):
    '''
    Pitch class
    '''
    __tablename__ = 'pitches'

    id = db.Column(db.Integer, primary_key = True)
    category_pitch = db.Column(db.String)
    pitch_body = db.Column(db.String)
    posted = db.Column(db.DateTime, default = datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
#    comments = db.relationship('Comment', backref = 'pitch', lazy = 'dynamic')

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_all_pitches(cls):
        pitches = Pitch.query.all()
        return pitches

class Comment(db.Model):
    '''
    Comment class
    '''
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key = True)
    comment_body = db.Column(db.String)
    posted = db.Column(db.DateTime, default = datetime.utcnow)
#    pitch_id = db.Column(db.Integer, db.ForeignKey('pitches.id'))
    pitches_id = db.Column(db.Integer)

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_all_comments(cls):
        comments = Comment.query.all()
        return comments

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import Required, Length


class PitchForm(FlaskForm):
    pitch = TextAreaField('New Pitch', validators=[Required(), Length(max=150)])
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.', validators=[Required()])
    submit = SubmitField('Submit')


class DeleteUser(FlaskForm):
    submit = SubmitField('Delete account')

class NewComment(FlaskForm):
    comment = TextAreaField('New Comment', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_mail import Mail

bootstrap = Bootstrap()
db = SQLAlchemy()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos', IMAGES)
mail = Mail()

def create_app(config_name):

    app = Flask(__name__)

    #creating app configurations
    app.config.from_object(config_options[config_name])

    #initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    #configure UploadSet
    configure_uploads(app, photos)

    #registering blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix = '/authenticate')
    
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views, error

app/main/views.py
from flask import render_template, request, redirect, url_for, abort
from . import main
from ..models import User, Pitch, Comment
from .forms import DeleteUser, UpdateProfile, PitchForm, NewComment
from .. import db, photos
from flask_login import login_required, current_user




@main.route('/')
def index():
    '''
    View root page function that returns the index page and its data
    '''
    return render_template('index.html')


@main.route('/user/<uname>', methods = ['GET', 'POST'])
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    form = DeleteUser()
    pitches = Pitch.get_all_pitches()

    
    print(pitches)
    if user is None:
        abort(404)
    elif form.validate_on_submit():
        db.session.delete(user)
        db.session.commit()

        return redirect(url_for('main.index'))
    else:

        return render_template('profile/profile.html', user = user, delete = form, pitches = pitches)

@main.route('/user/<uname>/update', methods = ['GET', 'POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    

    if user is None:
        abort(404)

    form = UpdateProfile()


    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile', uname = user.username))
    
    return render_template('profile/update.html', form = form)

@main.route('/user/<uname>/update/pic', methods  = ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile', uname = uname))

@main.route('/category/<category>')
def show_pitches(category):
    '''
    function that will show the pitches under a certain category
    '''
    pitches = Pitch.get_all_pitches()
    catego = category
    spec_pitches = []
    categ_name = category.split('-')
    categ = " ".join(categ_name).title()

    

    for pitch in pitches:
        if pitch.category_pitch == catego:
            spec_pitches.insert(0, pitch)
    


    return render_template('pitches_for_cat.html', category = catego, categ_formatted = categ, pitches = spec_pitches)

@main.route('/category/<category>/new_pitch', methods = ['GET', 'POST'])
@login_required
def new_pitch(category):
    form = PitchForm()
    categ = category

    if form.validate_on_submit():
        pitch = form.pitch.data

        new_pitches = Pitch(category_pitch = categ, pitch_body = pitch, user = current_user)
        new_pitches.save_pitch()

        return redirect(url_for('main.show_pitches', category = categ))

    return render_template('new_pitch.html', form = form)

@main.route('/pitch/comments/<pitch_id>')
def show_comments(pitch_id):
    comments = Comment.get_all_comments()
    pitch = Pitch.query.filter_by(id = pitch_id).first()
    
    pitchid = pitch.id
    spec_comments = []

    print(comments)

    for comment in comments:
        if comment.pitches_id == pitchid:
            spec_comments.insert(0, comment)

    print(spec_comments)

    return render_template('comments.html', pitch = pitch, comments = spec_comments)

@main.route('/pitch/comments/new_comment/<pitch_id>', methods = ['GET', 'POST'])
@login_required
def new_comments(pitch_id):
    form = NewComment()
    

    if form.validate_on_submit():
        comment = form.comment.data

        new_comment = Comment(comment_body = comment, pitches_id = pitch_id)
        new_comment.save_comment()

        return redirect(url_for('main.show_comments', pitch_id = pitch_id ))

    return render_template('new_comment.html', form = form)

app/templates/base.html
{% extends 'bootstrap/base.html' %}

<!--Navbar block-->
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/comments.html
{% extends 'base.html' %}

{% block styles %}
    {{super()}}
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&family=Satisfy&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Cookie&family=Satisfy&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet">
{% endblock %}


{% block content %}
<div class="container-fluid" style="background-color: black;">
<div class="container" style="font-family: 'Noto Sans JP', sans-serif; background-color: white;">
    <h4><strong>Pitch: </strong>{{pitch.pitch_body}}</h4>
    <hr>
    <h4><strong>Comments: </strong></h4>
    <hr>
    {% if comments %}
    <div style="text-align: left;">
        <br>
        <a href="/pitch/comments/new_comment/{{pitch.id}}"><button class="btn btn-secondary" style="text-align: center;"> Add comment</button></a>
    </div>
    <hr>
    <ul>
        {% for comment in comments %}
            
            <li>
                <div class="card">
                    <div class="card-header">
                        <p>{{comment.comment_body}}</p>
                    </div>
                    <div class="card-footer">
                        <p>Posted on : {{comment.posted}} (UTC TIME)</p>
                    </div>
                </div>
                
                
                
            </li>
            <hr>
            
        {% endfor %}
    </ul>
    {% else %}
        <h4 style="text-align: center;">No comments yet for this pitch, add one by clicking the button below</h4>
        <div style="text-align: center;">
            <br>
            <a href="/pitch/comments/new_comment/{{pitch.id}}"><button class="btn btn-secondary" style="text-align: center;"> Add comment</button></a>
        </div>
    {% endif %}
</div>
</div>


{% endblock %}

app/templates/error_page.html
{% extends 'base.html' %}


{% block content %}
<div class="alert alert-danger" role="alert">
    <h1 class="text-center"><b>Sorry, page not found</b></h1>
    <hr>
    <p class="text-center">Please check your URL!</p>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block styles %}
    {{super()}}
    
    <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet">
{% endblock %}


{% block content %}
<div class="container-fluid" style="background-color: black;">
<div class="container" style=" font-family: 'Fredoka One', cursive; color: black; background-color: white; ">
    <div style="background-color: white;">    
        <h1 style="text-align: center; ">Welcome to One Min Pitch App!</h1>
        <hr>
   
        <h4 style="text-align: center; ">Users post their one minute pitches in specific categories, and other users can vote for their favourite pitches and give feedback!</h4> 
        <h4 style="text-align: center; ">Click on any of the categories below to see the pitches posted under each!</h4>
    
    </div>
    


    <div class="row">
    <div class="col-md-6" style="padding: 30px; "> 
        <div class="card" style="background-color: black;" > 
            <div class="class-header">
                <h3 style="text-align: center;"><a href="/category/pick-up-lines" style="color: coral;" >Pick up lines</a></h3>
            </div>
            <hr>
            <div class="card-body" style="text-align: center;">
                <img class="card-img-body" src="" alt="">
                
                <div class="card-footer">
                    
                    
                    <hr>
                </div>
                
            </div>
        </div>
    </div>
    <div class="col-md-6" style="padding: 30px;" > 
        <div class="card" style="background-color: black;"> 
            <div class="class-header">
                <h3 style="text-align: center;"><a href="/category/quotes" style="color: coral;">Quotes</a></h3>
            </div>
            <hr>
            <div class="card-body" style="text-align: center;">
                <img class="card-img-body" src="" alt="">
                
                <div class="card-footer">
                    
                    
                    <hr>
                </div>
                
            </div>
        </div>
    </div>
    </div>
    <div class="row">
        <div class="col-md-6" style="padding: 30px;"> 
            <div class="card" style="background-color: black;"> 
                <div class="class-header">
                    <h3 style="text-align: center;"><a href="/category/dry-jokes" style="color: coral;">Dry jokes</a></h3>
                </div>
                <hr>
                <div class="card-body" style="text-align: center;">
                    <img class="card-img-body" src="" alt="">
                    
                    <div class="card-footer">
                        
                        
                        <hr>
                    </div>
                    
                </div>
            </div>
        </div>
        <div class="col-md-6" style="padding: 30px;"> 
            <div class="card" style="background-color: black;"> 
                <div class="class-header">
                    <h3 style="text-align: center;"><a href="/category/product-pitch" style="color: coral;">Product pitch</a></h3>
                </div>
                <hr>
                <div class="card-body" style="text-align: center;">
                    <img class="card-img-body" src="" alt="">
                    
                    <div class="card-footer">
                        
                        
                        <hr>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6" style="padding: 30px;"> 
            <div class="card" style="background-color: black;"> 
                <div class="class-header">
                    <h3 style="text-align: center;"><a href="/category/movie-pitch" style="color: coral;">Movie pitch</a></h3>
                </div>
                <hr>
                <div class="card-body" style="text-align: center;">
                    <img class="card-img-body" src="" alt="">
                    
                    <div class="card-footer">
                        
                        
                        <hr>
                    </div>
                    
                </div>
            </div>
        </div>
        <div class="col-md-6" style="padding: 30px;"> 
            <div class="card" style="background-color: black;"> 
                <div class="class-header">
                    <h3 style="text-align: center;"><a href="/category/book-pitch" style="color: coral;">Book pitch</a></h3>
                </div>
                <hr>
                <div class="card-body" style="text-align: center;">
                    <img class="card-img-body" src="" alt="">
                    
                    <div class="card-footer">
                        
                        
                        <hr>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation" style="background-color: black;">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand" style="font-size: 20pt;">ONE MIN PITCH</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                    <li style="color:white;padding:15px;">{{current_user.username}}</li>
                    <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                    <li><a href="{{url_for('auth.logout')}}">Sign Out</a></li>
                {% else %}
                    <li><a href="{{url_for('auth.login')}}">Sign In</a></li>
                {% endif %}

            </ul>
        </div>
    </div>
</div>

app/templates/new_comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container-fluid" style="background-color: black;">
    <div class="container" style="background-color: white;">
        {{wtf.quick_form(form)}}
    </div>
</div>

{% endblock %}

app/templates/new_pitch.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container-fluid" style="background-color: black; height: 100%;" >
<div class="container" style="background-color: white;">
    {{wtf.quick_form(form)}}
</div>
</div>
{% endblock %}

app/templates/pitches_for_cat.html
{% extends 'base.html' %}

{% block styles %}
    {{super()}}
    
    <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet">
{% endblock %}



{% block content %}
<div class="container-fluid" style="background-color: black;">
<div class="container" style="font-family: 'Fredoka One', cursive; background-color: white;">
    {% if pitches %}
    <h1 style="text-align: center; color: black;">Pitches for {{categ_formatted}} category</h1>
    <div style="text-align: center;">
        <br>
        <a href="/category/{{category}}/new_pitch"><button class="btn btn-secondary" style="text-align: center; font-size: x-large;"> Click here to add a pitch</button></a>
    </div>
    <hr>
    <div class="row">
        {% for pitch in pitches %}
        {% if pitch.user != None %}
        <div class="col-md-12">
           <div class="col-md-3"></div>
                <div class="col-md-6" style="padding: 30px;"> 
                    <div class="card"  style="color: black; background-color:beige;"> 
                        <div class="class-header" style="text-align: center; background-color: black; padding: 20px;">
                            <h4 style="font-size: x-large; color: maroon;">{{pitch.pitch_body}}</h4>
                            <h3 style="color: maroon; font-size: medium;"><em> ~by {{pitch.user}}</em></h3>
                        </div>
                        <br>
                        <div class="card-body" style="text-align: center; font-size: x-large; ">
                            <a href=""><span class="fas fa-thumbs-up"></span></a>
                            <br>
                            <button class="btn btn-primary btn-sm" style="font-size: medium;"> Upvote + </button> | <button class="btn btn-danger btn-sm" style="font-size: medium;">Downvote -</button> 
                            <br>
                            <br>
                            <p><a href="/pitch/comments/{{pitch.id}}" style="font-size: large; color: maroon;">Click here to view and add comments</a></p>
                            <br>
                            <div class="card-footer" style="font-size: large;">
                                
                                <p>Date posted: {{pitch.posted}} (UTC TIME)</p>
                                
                                <hr>
                            </div>
                            
                        </div>
                    </div>
                </div>
            <div class="col-md-3"></div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    {% else %}
        <h3 style="text-align: center;">No pitches yet for this category, add one by clicking the button below</h3>
        <div style="text-align: center;">
            <br>
            <a href="/category/{{category}}/new_pitch"><button class="btn btn-secondary" style="text-align: center;"> Add pitch</button></a>
        </div>
        {% endif %}
</div>
 
</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block styles %}
    {{super()}}
    
    <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet">
{% endblock %}


{% block content %}
<div class="container" style="font-family: 'Fredoka One'; color: black;">
    <h1 style="text-align: center;"><strong>{{user.username| capitalize}}</strong></h1>
    <hr>
    <div class="row">
        <div class="col-md-4" style="text-align: center;">
            
            <hr>
            {% if user.bio %}
                <h4><strong>Bio :</strong></h4>
                <p>{{user.bio}}</p>
                
            {% else %}
                <p>{{user.username| capitalize}} has no bio</p>
                <hr>
                
            {% endif %}

            
        
        </div>
        <div class="col-md-4" style="padding: 30px; text-align: center;">
            {% if user.profile_pic_path %}
            <img src="{{url_for('static', filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {% else %}
            <p>No profile picture</p>
            {% endif %}

            {% if user == current_user %}
            <form action="{{url_for('main.update_pic', uname = user.username)}}" method="POST" enctype="multipart/form-data">
                <input type="file" name="photo" class="form-control" required>
                <input type="submit">
            </form>
            {% endif %}
            
        </div>
        <div class="col-md-4">
            <hr>
            {% if user == current_user %}
                <a href="{{url_for('main.update_profile', uname=user.username)}}"><h4>Edit profile</h4></a>
            {% endif %}
           
            <hr>
            <hr>
            
            
            
          </div>
    </div>
    <hr>
    <div class="row">
        <h2 style="text-align: center;"><strong>My Pitches: </strong></h2>
           
            {% if pitches %}
           
                {% for pitch in pitches %}
               
                    {% if pitch.user_id == user.id %}
                     
                    <div class="col-md-6">
                        
                    <div class="card" style="text-align: center;">
                        <div class="card-header">
                            <h4> {{pitch.pitch_body}}.<span style="color: brown;">(category: {{pitch.category_pitch}})</span> </h4>
                        </div>
                        <br>
                        <div class="card-body">
                            <p></p>
                        </div>
                    </div>
                    <hr>
                    </div>
                    {% endif %}
               
                
                {% endfor %}
            {% else %}            
                <p>You have no pitches yet </p>
            {% endif %}

    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/single_pitch_comments.html
{% extends 'base.html' %}